version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    privileged: true
    network_mode: host

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./internal/metrics/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./internal/metrics/alerts.yml:/etc/prometheus/alerts.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./internal/metrics/grafanadata:/var/lib/grafana
    links:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./internal/metrics/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus
